"""Generate a piano-roll .pyscript with notes baked in.

File I/O is blocked inside FL's pyscript sandbox (BOTH read and write on FL
25.2.5 -- confirmed by probe). So we can't hand note data to a generic script
via a job file. Instead the daemon (a normal process, which CAN write files)
GENERATES the .pyscript itself with the notes embedded as a Python literal,
writes it to FL's "Piano roll scripts" folder, and triggers it. FL re-reads
the file on each trigger (confirmed), so overwrite + re-trigger applies fresh
notes. The script only ever calls addNote -- no file I/O inside FL.

Notes are specified in musical units (bars); the GENERATED script converts to
ticks at runtime using the live score.PPQ, so it's PPQ-agnostic.
"""

from __future__ import annotations

import os

PIANO_ROLL_SCRIPTS_DIR = os.path.expanduser(
    "~/Documents/Image-Line/FL Studio/Settings/Piano roll scripts"
)
APPLY_SCRIPT_NAME = "MCP_Apply.pyscript"

_DEFAULT_VELOCITY = 100 / 127.0

_TEMPLATE = """# Script.Name = "MCP Apply"
# Script.Category = "MCP"
# AUTO-GENERATED by fl-studio-mcp. Do not edit -- overwritten on each apply.

import flpianoroll as flp

MODE = {mode!r}        # "replace" clears the pattern first; "append" adds
NOTES = {notes!r}      # (pitch, time_bars, length_bars, velocity 0..1)


def _run():
    score = flp.score
    bar = score.PPQ * 4
    if MODE == "replace":
        try:
            score.clearNotes(True)     # FL 25.2.5: positional, no keyword
        except TypeError:
            score.clearNotes()
    for pitch, t_bars, len_bars, vel in NOTES:
        n = flp.Note()
        n.number = int(pitch)
        n.time = int(round(t_bars * bar))
        n.length = max(1, int(round(len_bars * bar)))
        n.velocity = float(vel)
        score.addNote(n)


def _go():
    undo = getattr(flp.score, "undoSection", None)
    if callable(undo):
        try:
            with undo():
                _run()
            return
        except Exception:
            pass
    _run()


_go()
"""


def render_apply_script(notes, mode="replace"):
    """Return the .pyscript source text for the given notes.

    notes: iterable of dicts {pitch, time_bars, length_bars, velocity}.
    """
    tuples = []
    for n in notes:
        tuples.append(
            (
                int(n["pitch"]),
                float(n.get("time_bars", 0.0)),
                float(n.get("length_bars", 1.0)),
                float(n.get("velocity", _DEFAULT_VELOCITY)),
            )
        )
    return _TEMPLATE.format(mode=mode, notes=tuples)


def write_apply_script(notes, mode="replace", scripts_dir=None):
    """Write the generated apply-script into FL's Piano roll scripts folder.

    Returns the path written.
    """
    scripts_dir = scripts_dir or PIANO_ROLL_SCRIPTS_DIR
    text = render_apply_script(notes, mode)
    path = os.path.join(scripts_dir, APPLY_SCRIPT_NAME)
    with open(path, "w", encoding="ascii") as f:
        f.write(text)
    return path


# ---------------------------------------------------------------------------
# Quantize
# ---------------------------------------------------------------------------


def quantize_notes(notes, grid_bars, snap_ends=False):
    """Snap each note's start (and optionally length) to a grid, in BARS. PURE.

    grid_bars: 0.0625 = 1/16, 0.125 = 1/8, 0.25 = 1/4. grid_bars <= 0 -> unchanged.
    Used to quantize notes we GENERATE before writing them.
    """
    g = float(grid_bars or 0)
    if g <= 0:
        return [dict(n) for n in notes]
    out = []
    for n in notes:
        m = dict(n)
        m["time_bars"] = round(round(float(n.get("time_bars", 0.0)) / g) * g, 6)
        if snap_ends:
            m["length_bars"] = max(g, round(round(float(n.get("length_bars", g)) / g) * g, 6))
        out.append(m)
    return out


# Quantizes the notes ALREADY in the open piano roll: read every note, clear,
# re-add with start (and optionally length) snapped to the grid. Uses the same
# addNote path the apply script proved works. PPQ-agnostic (uses live score.PPQ).
_QUANTIZE_TEMPLATE = """# Script.Name = "MCP Apply"
# Script.Category = "MCP"
# AUTO-GENERATED by fl-studio-mcp (quantize). Do not edit -- overwritten.

import flpianoroll as flp

GRID_BARS = {grid!r}     # snap resolution in bars (0.0625 = 1/16)
SNAP_ENDS = {ends!r}     # also snap note lengths to the grid


def _run():
    score = flp.score
    step = max(1, int(round(GRID_BARS * score.PPQ * 4)))
    notes = []
    for i in range(score.noteCount):
        n = score.getNote(i)
        notes.append((n.number, n.time, n.length, n.velocity))
    if not notes:
        return
    try:
        score.clearNotes(True)
    except TypeError:
        score.clearNotes()
    for num, t, ln, vel in notes:
        m = flp.Note()
        m.number = num
        m.time = int(round(t / step) * step)
        m.length = max(step, int(round(ln / step) * step)) if SNAP_ENDS else ln
        m.velocity = vel
        score.addNote(m)


def _go():
    undo = getattr(flp.score, "undoSection", None)
    if callable(undo):
        try:
            with undo():
                _run()
            return
        except Exception:
            pass
    _run()


_go()
"""


def render_quantize_script(grid_bars, snap_ends=False):
    return _QUANTIZE_TEMPLATE.format(grid=float(grid_bars), ends=bool(snap_ends))


def write_quantize_script(grid_bars, snap_ends=False, scripts_dir=None):
    """Write the quantize-existing-notes script to MCP_Apply.pyscript. Returns path."""
    scripts_dir = scripts_dir or PIANO_ROLL_SCRIPTS_DIR
    text = render_quantize_script(grid_bars, snap_ends)
    path = os.path.join(scripts_dir, APPLY_SCRIPT_NAME)
    with open(path, "w", encoding="ascii") as f:
        f.write(text)
    return path


# ---------------------------------------------------------------------------
# Transpose
# ---------------------------------------------------------------------------


_TRANSPOSE_TEMPLATE = """# Script.Name = "MCP Apply"
# Script.Category = "MCP"
# AUTO-GENERATED by fl-studio-mcp (transpose). Do not edit -- overwritten.

import flpianoroll as flp

SEMITONES = {semitones!r}


def _run():
    score = flp.score
    notes = []
    for i in range(score.noteCount):
        n = score.getNote(i)
        new_pitch = max(0, min(127, n.number + SEMITONES))
        notes.append((new_pitch, n.time, n.length, n.velocity))
    if not notes:
        return
    try:
        score.clearNotes(True)
    except TypeError:
        score.clearNotes()
    for num, t, ln, vel in notes:
        m = flp.Note()
        m.number = num
        m.time = t
        m.length = ln
        m.velocity = vel
        score.addNote(m)


def _go():
    undo = getattr(flp.score, "undoSection", None)
    if callable(undo):
        try:
            with undo():
                _run()
            return
        except Exception:
            pass
    _run()


_go()
"""


def render_transpose_script(semitones: int) -> str:
    return _TRANSPOSE_TEMPLATE.format(semitones=int(semitones))


def write_transpose_script(semitones: int, scripts_dir: str | None = None) -> str:
    """Write the transpose script to MCP_Apply.pyscript. Returns path."""
    scripts_dir = scripts_dir or PIANO_ROLL_SCRIPTS_DIR
    text = render_transpose_script(semitones)
    path = os.path.join(scripts_dir, APPLY_SCRIPT_NAME)
    with open(path, "w", encoding="ascii") as f:
        f.write(text)
    return path
