"""Generate a piano-roll .pyscript with notes baked in.

File I/O is blocked inside FL's pyscript sandbox (BOTH read and write on FL
25.2.5 -- confirmed by probe). So we can't hand note data to a generic script
via a job file. Instead the daemon (a normal process, which CAN write files)
GENERATES the .pyscript itself with the notes embedded as a Python literal,
writes it to FL's "Piano roll scripts" folder, and triggers it. FL re-reads
the file on each trigger (confirmed), so overwrite + re-trigger applies fresh
notes. The script only ever calls addNote -- no file I/O inside FL.

Notes are specified in musical units (bars); the GENERATED script converts to
ticks at runtime using the live score.PPQ, so it's PPQ-agnostic.
"""

from __future__ import annotations

import os

PIANO_ROLL_SCRIPTS_DIR = os.path.expanduser(
    "~/Documents/Image-Line/FL Studio/Settings/Piano roll scripts"
)
APPLY_SCRIPT_NAME = "MCP_Apply.pyscript"

_DEFAULT_VELOCITY = 100 / 127.0

_TEMPLATE = '''# Script.Name = "MCP Apply"
# Script.Category = "MCP"
# AUTO-GENERATED by fl-studio-mcp. Do not edit -- overwritten on each apply.

import flpianoroll as flp

MODE = {mode!r}        # "replace" clears the pattern first; "append" adds
NOTES = {notes!r}      # (pitch, time_bars, length_bars, velocity 0..1)


def _run():
    score = flp.score
    bar = score.PPQ * 4
    if MODE == "replace":
        try:
            score.clearNotes(True)     # FL 25.2.5: positional, no keyword
        except TypeError:
            score.clearNotes()
    for pitch, t_bars, len_bars, vel in NOTES:
        n = flp.Note()
        n.number = int(pitch)
        n.time = int(round(t_bars * bar))
        n.length = max(1, int(round(len_bars * bar)))
        n.velocity = float(vel)
        score.addNote(n)


def _go():
    undo = getattr(flp.score, "undoSection", None)
    if callable(undo):
        try:
            with undo():
                _run()
            return
        except Exception:
            pass
    _run()


_go()
'''


def render_apply_script(notes, mode="replace"):
    """Return the .pyscript source text for the given notes.

    notes: iterable of dicts {pitch, time_bars, length_bars, velocity}.
    """
    tuples = []
    for n in notes:
        tuples.append((
            int(n["pitch"]),
            float(n.get("time_bars", 0.0)),
            float(n.get("length_bars", 1.0)),
            float(n.get("velocity", _DEFAULT_VELOCITY)),
        ))
    return _TEMPLATE.format(mode=mode, notes=tuples)


def write_apply_script(notes, mode="replace", scripts_dir=None):
    """Write the generated apply-script into FL's Piano roll scripts folder.

    Returns the path written.
    """
    scripts_dir = scripts_dir or PIANO_ROLL_SCRIPTS_DIR
    text = render_apply_script(notes, mode)
    path = os.path.join(scripts_dir, APPLY_SCRIPT_NAME)
    with open(path, "w", encoding="ascii") as f:
        f.write(text)
    return path
